// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recursive.proto

package org.apache.hudi.utilities.test.proto;

public interface ChildOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Child)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 basic_field = 1;</code>
   */
  int getBasicField();

  /**
   * <code>.test.Child recurse_field = 2;</code>
   */
  boolean hasRecurseField();
  /**
   * <code>.test.Child recurse_field = 2;</code>
   */
  org.apache.hudi.utilities.test.proto.Child getRecurseField();
  /**
   * <code>.test.Child recurse_field = 2;</code>
   */
  org.apache.hudi.utilities.test.proto.ChildOrBuilder getRecurseFieldOrBuilder();
}
