// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recursive.proto

package org.apache.hudi.utilities.test.proto;

/**
 * <pre>
 * Creates a message for testing the unravelling of recursive schemas
 * </pre>
 *
 * Protobuf type {@code test.Parent}
 */
public  final class Parent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.Parent)
    ParentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Parent.newBuilder() to construct.
  private Parent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Parent() {
    children_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Parent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.apache.hudi.utilities.test.proto.Child.Builder subBuilder = null;
            if (child_ != null) {
              subBuilder = child_.toBuilder();
            }
            child_ = input.readMessage(org.apache.hudi.utilities.test.proto.Child.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(child_);
              child_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              children_ = new java.util.ArrayList<org.apache.hudi.utilities.test.proto.Child>();
              mutable_bitField0_ |= 0x00000002;
            }
            children_.add(
                input.readMessage(org.apache.hudi.utilities.test.proto.Child.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        children_ = java.util.Collections.unmodifiableList(children_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.hudi.utilities.test.proto.Recursive.internal_static_test_Parent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.hudi.utilities.test.proto.Recursive.internal_static_test_Parent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.hudi.utilities.test.proto.Parent.class, org.apache.hudi.utilities.test.proto.Parent.Builder.class);
  }

  private int bitField0_;
  public static final int CHILD_FIELD_NUMBER = 1;
  private org.apache.hudi.utilities.test.proto.Child child_;
  /**
   * <code>.test.Child child = 1;</code>
   */
  public boolean hasChild() {
    return child_ != null;
  }
  /**
   * <code>.test.Child child = 1;</code>
   */
  public org.apache.hudi.utilities.test.proto.Child getChild() {
    return child_ == null ? org.apache.hudi.utilities.test.proto.Child.getDefaultInstance() : child_;
  }
  /**
   * <code>.test.Child child = 1;</code>
   */
  public org.apache.hudi.utilities.test.proto.ChildOrBuilder getChildOrBuilder() {
    return getChild();
  }

  public static final int CHILDREN_FIELD_NUMBER = 2;
  private java.util.List<org.apache.hudi.utilities.test.proto.Child> children_;
  /**
   * <code>repeated .test.Child children = 2;</code>
   */
  public java.util.List<org.apache.hudi.utilities.test.proto.Child> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .test.Child children = 2;</code>
   */
  public java.util.List<? extends org.apache.hudi.utilities.test.proto.ChildOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .test.Child children = 2;</code>
   */
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .test.Child children = 2;</code>
   */
  public org.apache.hudi.utilities.test.proto.Child getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .test.Child children = 2;</code>
   */
  public org.apache.hudi.utilities.test.proto.ChildOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (child_ != null) {
      output.writeMessage(1, getChild());
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(2, children_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (child_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChild());
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, children_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.hudi.utilities.test.proto.Parent)) {
      return super.equals(obj);
    }
    org.apache.hudi.utilities.test.proto.Parent other = (org.apache.hudi.utilities.test.proto.Parent) obj;

    boolean result = true;
    result = result && (hasChild() == other.hasChild());
    if (hasChild()) {
      result = result && getChild()
          .equals(other.getChild());
    }
    result = result && getChildrenList()
        .equals(other.getChildrenList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChild()) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChild().hashCode();
    }
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.hudi.utilities.test.proto.Parent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.hudi.utilities.test.proto.Parent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Creates a message for testing the unravelling of recursive schemas
   * </pre>
   *
   * Protobuf type {@code test.Parent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Parent)
      org.apache.hudi.utilities.test.proto.ParentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hudi.utilities.test.proto.Recursive.internal_static_test_Parent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hudi.utilities.test.proto.Recursive.internal_static_test_Parent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.hudi.utilities.test.proto.Parent.class, org.apache.hudi.utilities.test.proto.Parent.Builder.class);
    }

    // Construct using org.apache.hudi.utilities.test.proto.Parent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChildrenFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (childBuilder_ == null) {
        child_ = null;
      } else {
        child_ = null;
        childBuilder_ = null;
      }
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.hudi.utilities.test.proto.Recursive.internal_static_test_Parent_descriptor;
    }

    public org.apache.hudi.utilities.test.proto.Parent getDefaultInstanceForType() {
      return org.apache.hudi.utilities.test.proto.Parent.getDefaultInstance();
    }

    public org.apache.hudi.utilities.test.proto.Parent build() {
      org.apache.hudi.utilities.test.proto.Parent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.apache.hudi.utilities.test.proto.Parent buildPartial() {
      org.apache.hudi.utilities.test.proto.Parent result = new org.apache.hudi.utilities.test.proto.Parent(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (childBuilder_ == null) {
        result.child_ = child_;
      } else {
        result.child_ = childBuilder_.build();
      }
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.hudi.utilities.test.proto.Parent) {
        return mergeFrom((org.apache.hudi.utilities.test.proto.Parent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.hudi.utilities.test.proto.Parent other) {
      if (other == org.apache.hudi.utilities.test.proto.Parent.getDefaultInstance()) return this;
      if (other.hasChild()) {
        mergeChild(other.getChild());
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.hudi.utilities.test.proto.Parent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.hudi.utilities.test.proto.Parent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.apache.hudi.utilities.test.proto.Child child_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder> childBuilder_;
    /**
     * <code>.test.Child child = 1;</code>
     */
    public boolean hasChild() {
      return childBuilder_ != null || child_ != null;
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child getChild() {
      if (childBuilder_ == null) {
        return child_ == null ? org.apache.hudi.utilities.test.proto.Child.getDefaultInstance() : child_;
      } else {
        return childBuilder_.getMessage();
      }
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public Builder setChild(org.apache.hudi.utilities.test.proto.Child value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        child_ = value;
        onChanged();
      } else {
        childBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public Builder setChild(
        org.apache.hudi.utilities.test.proto.Child.Builder builderForValue) {
      if (childBuilder_ == null) {
        child_ = builderForValue.build();
        onChanged();
      } else {
        childBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public Builder mergeChild(org.apache.hudi.utilities.test.proto.Child value) {
      if (childBuilder_ == null) {
        if (child_ != null) {
          child_ =
            org.apache.hudi.utilities.test.proto.Child.newBuilder(child_).mergeFrom(value).buildPartial();
        } else {
          child_ = value;
        }
        onChanged();
      } else {
        childBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public Builder clearChild() {
      if (childBuilder_ == null) {
        child_ = null;
        onChanged();
      } else {
        child_ = null;
        childBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child.Builder getChildBuilder() {
      
      onChanged();
      return getChildFieldBuilder().getBuilder();
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    public org.apache.hudi.utilities.test.proto.ChildOrBuilder getChildOrBuilder() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilder();
      } else {
        return child_ == null ?
            org.apache.hudi.utilities.test.proto.Child.getDefaultInstance() : child_;
      }
    }
    /**
     * <code>.test.Child child = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder> 
        getChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder>(
                getChild(),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }

    private java.util.List<org.apache.hudi.utilities.test.proto.Child> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        children_ = new java.util.ArrayList<org.apache.hudi.utilities.test.proto.Child>(children_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public java.util.List<org.apache.hudi.utilities.test.proto.Child> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder setChildren(
        int index, org.apache.hudi.utilities.test.proto.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder setChildren(
        int index, org.apache.hudi.utilities.test.proto.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder addChildren(org.apache.hudi.utilities.test.proto.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder addChildren(
        int index, org.apache.hudi.utilities.test.proto.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder addChildren(
        org.apache.hudi.utilities.test.proto.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder addChildren(
        int index, org.apache.hudi.utilities.test.proto.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends org.apache.hudi.utilities.test.proto.Child> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public org.apache.hudi.utilities.test.proto.ChildOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public java.util.List<? extends org.apache.hudi.utilities.test.proto.ChildOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          org.apache.hudi.utilities.test.proto.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public org.apache.hudi.utilities.test.proto.Child.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, org.apache.hudi.utilities.test.proto.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Child children = 2;</code>
     */
    public java.util.List<org.apache.hudi.utilities.test.proto.Child.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.hudi.utilities.test.proto.Child, org.apache.hudi.utilities.test.proto.Child.Builder, org.apache.hudi.utilities.test.proto.ChildOrBuilder>(
                children_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.Parent)
  }

  // @@protoc_insertion_point(class_scope:test.Parent)
  private static final org.apache.hudi.utilities.test.proto.Parent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.hudi.utilities.test.proto.Parent();
  }

  public static org.apache.hudi.utilities.test.proto.Parent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Parent>
      PARSER = new com.google.protobuf.AbstractParser<Parent>() {
    public Parent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Parent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Parent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Parent> getParserForType() {
    return PARSER;
  }

  public org.apache.hudi.utilities.test.proto.Parent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

