// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package org.apache.hudi.utilities.test.proto;

public interface WithOneOfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.WithOneOf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 int = 1;</code>
   */
  int getInt();

  /**
   * <code>int64 long = 2;</code>
   */
  long getLong();

  /**
   * <code>.test.Nested message = 3;</code>
   */
  boolean hasMessage();
  /**
   * <code>.test.Nested message = 3;</code>
   */
  org.apache.hudi.utilities.test.proto.Nested getMessage();
  /**
   * <code>.test.Nested message = 3;</code>
   */
  org.apache.hudi.utilities.test.proto.NestedOrBuilder getMessageOrBuilder();

  public org.apache.hudi.utilities.test.proto.WithOneOf.SomeValueCase getSomeValueCase();
}
